<h1>Add Article</h1>

<form method="POST">
    <div class="controls controls-row">
        <input name="title" class="span6" type="text" placeholder="Title">
        <input name="author" class="span2" type="text" placeholder="Author">
    </div>
    <div class="controls controls-row">
        <textarea name="content" class="span8" placeholder="Content" rows="10"></textarea>
    </div>
    <div class="controls controls-row">
        <a class="btn" href="/news"><em class="icon-chevron-left"></em> Cancel</a>
        <button class="btn btn-success"><em class="icon-plus icon-white"></em> Save</button>
    </div>
</form>